config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, :controllers => { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/author/:author_name', to: 'posts#author_posts'
  
  get '/tag/:tag_name', to: 'posts#tag_posts'
  post '/tag/new', to: 'tags#new', as: :new_tag
  put '/tags/:id', to: 'tags#update'
  delete '/tags/:id', to: 'tags#delete'

  post '/save_collapse_state/', to: 'posts#save_collapse_state', as: :save_collapse_state
  post '/sort_posts/', to: 'posts#sort_posts', as: :sort_posts

  root to: "posts#index"

end

app/models/post.rb
class Post < ApplicationRecord
    # Validations
    validates :title, presence: true, 
        length: { 
            in: 10..100,
            too_long: "%{count} characters is the longest title allowed.",
            too_sort: "%{count} characters is the shortest title allowed."
        }
    validates :summary, presence: true, 
        length: { 
            in: 20..300,
            too_long: "%{count} characters is the longest summary allowed.",
            too_sort: "%{count} characters is the shortest summary allowed."
        }
    validates :content, presence: true
    
    # Relationships
    has_many :posttags
    has_many :tags, through: :posttags
    belongs_to :author
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_sorting_method_names
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_author!, only: [:new, :edit, :create, :update]

  # POST /save_collapse_state/
  def save_collapse_state
    session[:list_collapsed] = collapse_param["list_collapsed"] == "true" ? true : false 
  end 

  # POST /sort_posts/
  def sort_posts
    session[:sorting_method] = sort_param["method"]
    redirect_back fallback_location: :root
  end 


  # GET /tag/complexity_theory
  def tag_posts
    @tag = Tag.where('lower(name) = ?', params["tag_name"].downcase).first
    if @tag
      @posts = @tag.posts
      sort_posts_by_method(session[:sorting_method])
    else 
      redirect_to :root
    end 
  end 

  # GET /author/walker
  def author_posts
    @author = Author.where('lower(name) = ?', params["author_name"].downcase).first
    if @author 
      @posts = @author.posts
      sort_posts_by_method(session[:sorting_method])
    else 
      redirect_to :root
    end 
  end 

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    sort_posts_by_method(session[:sorting_method])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @initial_tags = Tag.all.map {|tag| tag.name }
    @current_tags = []
  end

  # GET /posts/1/edit
  def edit
    if @post.author == current_author 
      @initial_tags = Tag.all.map {|tag| tag.name }
      @current_tags = @post.tags.map {|tag| tag.name }
    else
      redirect_to :root 
    end 
  end

  # POST /posts
  # POST /posts.json
  def create
    tags = params["post_tags"].split(',')
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        Posttag.add_tags_to_post(@post, tags)
        format.html { redirect_to :root, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    tags = params["post_tags"].split(',')
    respond_to do |format|
      if @post.update(post_params)
        Posttag.add_tags_to_post(@post, tags)
        format.html { redirect_to :root, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # All methods used for sorting the posts when they are shown
    def sorting_methods
      return {
        'Title' => {
          'A to Z' => Proc.new { |posts| posts.sort_by { |post| post.title.downcase } }, 
          'Z to A' => Proc.new { |posts| posts.sort_by { |post| post.title.downcase }.reverse }
        },

        'Date Posted' => {
          'Most Recent First' => Proc.new { |posts| posts.sort_by { |post| post.created_at }.reverse },
          'Oldest First' => Proc.new { |posts| posts.sort_by { |post| post.created_at } }
        },

        'Length' => {
          'Longest First' => Proc.new { |posts| posts.sort_by { |post| post.content.length }.reverse },
          'Shortest First' => Proc.new { |posts| posts.sort_by { |post| post.content.length } }
        },

        'Number of Tags' => {
          'Most Tags First' => Proc.new { |posts| posts.sort_by { |post| post.tags.count }.reverse }, 
          'Least Tags First' => Proc.new { |posts| posts.sort_by { |post| post.tags.count } } 
        }
      }
    end 

    # The names of the <option> groups allowed for sorting posts
    def set_sorting_method_names
      @sorting_method_names = {}
      sorting_method_groups = sorting_methods
      sorting_method_groups.keys.each { |method_group| @sorting_method_names[method_group] = sorting_method_groups[method_group].keys }
    end   

    # Sorts the posts using the appropriate method
    def sort_posts_by_method(method)
      # Default to sorting lexigraphically
      if method == nil 
        session[:sorting_method] = 'A to Z'
        method = session[:sorting_method]
      end 
      # Sort posts using the appropriate procedure
      sorting_methods.each_value do |method_hash|
        @posts = method_hash.has_key?(method) ? method_hash[method].call(@posts) : @posts
      end 
    end 

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # White list the parameters used for sorting
    def sort_param
      params.require(:sorting_method).permit(:method)
    end 

    def collapse_param
      params.require(:collapse_state).permit(:list_collapsed)
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :title, :summary, :post_tags).merge(author_id: current_author.id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%
  # HTML Entities
  title_header = "<h2>#{ title }</h2>".html_safe
  post_tag_input = '
    <div class="row">
      <div class="col-xs-12 col-sm-4 dropdown">
        <label for="tagInput">Post Tags (<em>Optional</em>)</label>
        <input id="tagInput" type="text" class="form-control" placeholder="Tag Name" data-toggle="dropdown">
        <span class="dropdown-menu" id="dropdownMenu">
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" data-toggle="modal" data-target="#createNewTagModal">Create new tag...</a>
        </span>
      </div>
      <div class="col-xs-12 col-sm-8">
        <div id="tags"></div>
      </div>
    </div>'.html_safe
  # Ruby HTML Generators
  post_preview_container = Proc.new do |post|
    preview_content = post == nil || post.content == nil ? 'The post will appear here...' : post.content
    "<div class=\"row\">
      <div class=\"col-sm-12\">
        <div class=\"card\">
          <h5 class=\"card-header\">Post Preview</h5>
          <div class=\"card-body\">
            <div id=\"contentPreview\">#{HTMLEntities.new.decode(preview_content).html_safe}</div>
          </div>
        </div>
      </div>
    </div>".html_safe
  end 
%>

<%= form_with(model: post, local: true) do |form| %>

  <% if post.errors.any? %>
    <div class="row">
      <div class="col-xs-12 col-sm-10 offset-sm-1">
        <div class="alert alert-danger alert-dismissible fade show">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="alert-heading">Please fix the following <%= pluralize(post.errors.count, "error") %>:</h4>
          <ul>
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>

        </div>

      </div>
    </div>
  <% end %>

<div class="row">
  <div class="col-xs-12 col-sm-10 offset-sm-1">
    <div class="jumbotron" id="postJumbotron">
      
      <%= title_header %>
      
      <hr>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :post_title, class: 'form-control', placeholder: 'Your post\'s title' %>
      </div>

      <div class="form-group">
        <%= form.label :summary %>
        <%= form.text_field :summary, id: :post_summary, class: 'form-control', placeholder: 'A quick summary for your post' %>
      </div>
      
      
      <div class="form-group">
        <%= form.label :content %>
        <%= form.trix_editor :content, id: :post_content, placeholder: 'Write your post\'s stuff here' %>
      </div>

      <%= post_preview_container.call(post) %>
      
      <br>

      <%= post_tag_input %>

      <hr>

      <%= form.submit class: 'btn btn-info'%>

      <%= hidden_field_tag :post_tags,"", name: "post_tags" %>
    </div>
  </div>
</div>  
<% end %>

<%= render 'new_tag_modal' %>

<script>
  const initialTags = <%= raw @initial_tags %>;
  const currentTags = <%= raw @current_tags %>;
  let dropdownTags = [];
</script>

<%= javascript_include_tag 'post_tags' %>

app/views/posts/_new_tag_modal.html.erb
<%
  # HTML Entities
  close_modal_button = '
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>'.html_safe
%>
<div class="modal fade" id="createNewTagModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div id="modalBody" class="modal-body">

        <%= close_modal_button %>  

        <%= form_for :tag, url: :new_tag, remote: true do |f| %>
          <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, id: :tag_name, class: 'form-control', placeholder: 'The tag\'s name'%>
          </div>

          <div class="form-group">
              <%= f.label 'Description' %>
              <%= f.text_field :desc, id: :tag_desc, class: 'form-control', placeholder: 'A little description for what the tag represents' %>
          </div>

          <hr>

          <%= f.submit 'Create Tag', class: 'btn btn-success'%>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/posts/_summary_index.html.erb
<div class="col-12 col-sm-3 offset-sm-1">
  <div class="jumbotron jumbotron-fluid post-listing-jumbotron sticky-top">
    <div class="container">
      <h3><strong>Post List</strong></h3>
      <label for="sortingSelect">Sort the posts by</label>

      <%= form_for('sorting_method', url: :sort_posts) do |f| %>
        <%= f.select :method, {}, {}, { class: 'form-control', onchange: 'this.form.submit();' } do %>
          <%= grouped_options_for_select(@sorting_method_names, selected: session[:sorting_method]) %>
        <% end %>
      <% end %>
      <br>
      <ul class="list-group list-group-flush">
        <% posts.each do |post| %>
          <a class="list-group-item list-group-item-action" data-target="card<%= post.id %>"><%= post.title %></a>
        <% end %>
      </ul>
    </div>
  </div>
  <br>
</div>

app/views/posts/author_posts.html.erb
<%= render "posts/post_summaries_page/post_summaries_page", { posts: @posts, title: 'Posts by ' + @author.name } %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, title: 'Edit Post' %>

app/views/posts/index.html.erb
<%= render "posts/post_summaries_page/post_summaries_page", { posts: @posts, title: "All Posts" } %>

app/views/posts/new.html.erb
<%= render 'form', post: @post, title: 'Create a Post'%>

app/views/posts/show.html.erb
<%
  creation_time = @post.created_at.strftime("%A %B %e, %Y")
  contents = HTMLEntities.new.decode(@post.content).html_safe
  # HTML Entities
  post_title = "<h1 class=\"display-4\">#{@post.title}</h1>".html_safe
  post_details = "<p class=\"font-weight-light\">Written by #{@post.author.name} on #{creation_time}</p>".html_safe
  post_summary = "<p class=\"lead\">#{@post.summary}</p>".html_safe
  post_contents = "<p>#{ contents }</p>".html_safe
  hr_tag = '<hr class="my-4">'.html_safe
  
  # Ruby Generated HTML
  tag_link = Proc.new do |tag|
    link_to(tag.name, '/tag/' + tag.name, class:'btn btn-primary show-post-tag-buttons')
  end 
%>

<div class="row">
  <div class="col-xs-12 col-sm-10 offset-sm-1">
    <div class="jumbotron" id="postJumbotron">
      <%= post_title %>
      <%= post_details %>
      <%= post_summary %>
      <%= hr_tag %>
      <%= post_contents %>

      <br>

      <% @post.tags.each do |tag| %>
        <%= tag_link.call(tag) %>
      <% end %>

      <br>

      <%= hr_tag %>
      <%= link_to 'Back', 'javascript:history.back()', class: 'btn btn-outline-info' %>

      <% if @post.author == current_author %>
        <%= hr_tag %>
        <%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-info edit-post-btn' %>
        <%= link_to 'Delete Post', @post, method: :delete, class: 'btn btn-danger edit-post-btn' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/tag_posts.html.erb
<%= render "posts/post_summaries_page/post_summaries_page", { posts: @posts, title: "Posts about " + @tag.name } %>