config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, :controllers => { registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/author/:author_name', to: 'posts#author_posts'
  
  get '/tag/:tag_name', to: 'posts#tag_posts'
  post '/tag/new', to: 'tags#new', as: :new_tag
  put '/tags/:id', to: 'tags#update'
  delete '/tags/:id', to: 'tags#delete'

  post '/save_collapse_state/', to: 'posts#save_collapse_state', as: :save_collapse_state
  post '/sort_posts/', to: 'posts#sort_posts', as: :sort_posts

  root to: "posts#index"

end

app/views/layouts/site_navbar/_author_links_dropdown.html.erb
<%
    can_create_authors = (current_author != nil && current_author.id == 1)
    # Ruby Generated HTML
    author_creation_link = link_to('Create New Author', :new_author_registration, class: 'dropdown-item')
    # HTML Entities
    dropdown_button = "
    <button class=\"btn btn-light dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">
        #{current_author.name}
    </button>".html_safe
    dropdown_divider = '<div class="dropdown-divider"></div>'.html_safe
    edit_tags_modal_link = '<a class="dropdown-item edit-tags" data-toggle="modal" data-target="#editTagModal">Edit Post Tags</a>'.html_safe
%>

<div class="dropdown">    
    <%= dropdown_button %>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        
        <% # Link to post creation %>
        <%= link_to 'Create Post', :new_post, method: :get, class: 'btn btn-outline-success btn-block' %>      

        <%= dropdown_divider %>

        <% # Link to author's posts %>
        <%= link_to 'Your Posts', '/author/' + current_author.name, class: 'dropdown-item' %>

        <% # Link to editing author information %>
        <%= link_to 'Edit Your Profile', :edit_author_registration, class: 'dropdown-item' %>

        <% # Link to creating new authors %>
        <%= can_create_authors ? author_creation_link : '' %>
            
        <% if @can_remove_tags %>
            <%= dropdown_divider %>
            <%= edit_tags_modal_link %>
        <% end %>
        
        <%= dropdown_divider %>
        
        <%= link_to 'Logout', :destroy_author_session, method: :delete, class: 'dropdown-item' %>
    </div>
</div>

app/views/layouts/site_navbar/_navbar.html.erb
<%
  # HTML Entities
  navbar_toggle_button = '
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>'.html_safe
  author_login = link_to('Author Login', :new_author_session, method: :get, class: 'btn btn-info')
%>

<nav class="navbar fixed-top navbar-expand-lg application-navbar justify-content-between">
    <% # The Navbar's Brand %>
    <%= link_to 'The Bit Banging Blog', :root, class: 'navbar-brand'  %>
    
    <%= navbar_toggle_button %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <% # Link to every post on blog %>
        <li class="nav-item">
          <%= link_to 'All Posts', :root, class: 'nav-link'  %>
        </li>

        <% # Link to every author's posts on the blog %>
        <%= render 'layouts/site_navbar/posts_by_writer_dropdown' %>

        <% # Link to posts for every Tag on the blog %>
        <%= render 'layouts/site_navbar/posts_by_tag_dropdown' %>

      </ul>

      <div>
        <% # Either Login link or links for author %>
        <%= author_signed_in? ? render('layouts/site_navbar/author_links_dropdown') : author_login %>
      </div>

    </div>
</nav>
    
<% # Don't allow tag removal when creating new posts or updating old ones %>
<%= @can_remove_tags ? render("layouts/remove_tag_modal") : "" %>

app/views/layouts/site_navbar/_posts_by_tag_dropdown.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Posts By Topic
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <% Tag.all.each do |tag| %>
      <%= link_to '/tag/' + tag.name, class: 'dropdown-item' do %>
        <%= tag.name %> &nbsp;
        <span class="badge badge-info">
          <%= tag.posts.size %>
          <%= tag.posts.size == 1 ? " post" : " posts"%>
        </span>
      <% end %>  
    <% end %>
  </div>
</li>

app/views/layouts/site_navbar/_posts_by_writer_dropdown.html.erb
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Posts By Writer
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <% Author.all.each do |author| %>
            <% unless author.posts.count == 0 %>
                <%= link_to '/author/' + author.name, class: 'dropdown-item' do %>
                    <%= author.name %> &nbsp;
                    <span class="badge badge-info">
                        <%= author.posts.size %>
                        <%= (author.posts.size == 1 ? " post" : " posts") %>
                    </span>
                <% end %>
            <% end %>
        <% end %>
    </div>
</li>